#!/bin/sh

# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

# trash function
trash() {
    tr '\n' '\0' |
        xargs -0 realpath |
        sort -u
    # | while read -r file; do
    case "$(file -b -i "$file")" in
    *)
        trash-put "$file" &&
            notify-send \
                "sxiv" \
                "$file moved to trash" \
                --icon=messagebox_warning
        ;;
    esac
    # done
}

while read file; do
    # keybindings
    case "$1" in
    "g")
        tr '\n' '\0' |
            xargs -0 flatpak run org.gimp.GIMP//beta $file &
        ;;
    "d")
        trash
        ;;
    "w") feh --bg-fill "$file" &;;
    "y") realpath -z "$file" | tr -d '\0' | xsel --clipboard &&
         notify-send "$(readlink -f "$file") copied to clipboard" &;;
    "r")
        convert -rotate 90 "$file" "$file"
        ;;
    "R")
        convert -rotate -90 "$file" "$file"
        ;;
    "f")
        convert -flop "$file" "$file"
        ;;
    "c")
        [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
        [ -z "$destdir" ] && exit
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
        ;;
    "m")
        [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
        [ -z "$destdir" ] && exit
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
        ;;
    esac
done
