#!/bin/sh

# path:       /home/klassiker/.config/sxiv/exec/key-handler
# author:     klassiker [mrdotx]
# github:     https://github.com/mrdotx/dotfiles
# date:       2020-11-09T17:41:52+0100

# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

# rotate function
rotate() {
    degree="$1"
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                image/jpeg*)
                    jpegtran -rotate "$degree" -copy all -outfile "$file" "$file"
                    ;;
                *)
                    mogrify  -rotate "$degree" "$file"
                    ;;
            esac
        done
}

# flip function
flip() {
    direction="$1"
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                image/jpeg*)
                    jpegtran -flip "$direction" -copy all -outfile "$file" "$file"
                    ;;
                *)
                    if [ "$direction" = "horizontal" ]; then
                        mogrify -flop "$file"
                    elif [ "$direction" = "vertical" ]; then
                        mogrify -flip "$file"
                    fi
                    ;;
            esac
        done
}

# trash function
trash() {
    tr '\n' '\0' \
        | xargs -0 realpath \
        | sort -u \
        | while read -r file; do
            case "$(file -b -i "$file")" in
                *)
                    trash-put "$file" \
                        && notify-send \
                            "sxiv" \
                            "$file moved to trash" \
                            --icon=messagebox_warning
                    ;;
        esac
    done
}

# keybindings
case "$1" in
    "C-e")
        while read -r file; do $TERMINAL -T "$file" -e \
            sh -c "exiftool '$file' | less" \
            & done
        ;;
    "C-w")
        while read -r file; do [ -f "$file" ] \
            && convert "$file" ~/.local/share/wallpaper.jpg \
            && systemctl --user restart xwallpaper.service \
            & done
        ;;
    "C-g")
        tr '\n' '\0' \
            | xargs -0 gimp &
        ;;
    "C-comma")
        rotate 270
        ;;
    "C-period")
        rotate 90
        ;;
    "C-slash") # Ctrl + /
        rotate 180
        ;;
    "C-semicolon") # `Ctrl + ;`
        flip 'horizontal'
        ;;
    "C-apostrophe") # `Ctrl + '`
        flip 'vertical'
        ;;
    "C-d")
        trash
        ;;
	"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
	"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
	"C-k")      while read file; do kitty -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;

esac
